### ISSUE TITLE
Container doesn't build

### ISSUE THREAD

**Issue by gcbirzan** [sjoerdmulder/teamcity-agent-docker#10]
The get.docker.com link is invalid, it seems the correct one is: https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz.

**Comment by sjoerdmulder** [comment]
Yes i noticed :) The problem is that docker is now split into multiple files and i didn't have time to look into this...

Reverting back to 1.10 will work though

**Comment by sjoerdmulder** [comment]
This is fixed now
