### ISSUE TITLE
requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net fails

### ISSUE THREAD

**Issue by choesang** [sjoerdmulder/teamcity-agent-docker#11]
Hi,
Building the teamcity-agent fails when fetching the key from the server. 

`Step 7 : RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
 ---> Running in 98a558c8a93a
gpg: directory`/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in`/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring`/root/.gnupg/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
?: ha.pool.sks-keyservers.net: Network is unreachable
gpgkeys: HTTP fetch error 7: couldn't connect: Network is unreachable
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
ERROR: Service 'teamcity-agent-jdk8' failed to build: The command '/bin/sh -c gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4' returned a non-zero code: 2`

**Comment by sjoerdmulder** [comment]
Seems you have network issues while building. On docker hub everything works
