### ISSUE TITLE
How does teamcity agent's docker Runner Type for docker works?

### ISSUE THREAD

**Issue by lucernae** [sjoerdmulder/teamcity-agent-docker#14]
Hi @sjoerdmulder ,

I don't know what is the best place for me to direct this question. In summary, I've used your docker image for teamcity-agent. I used it from Rancher catalogue here: https://github.com/rancher/community-catalog/blob/master/templates/teamcity/0/docker-compose.yml (did you maintain this?).

I found out that the agent can't build docker image because of wrong permission. So, I'm going to ask how do you intend of making this work in the first place? Is it using shared docker socket from the host machine, or using docker-in-docker? For your information, in my installation, I modified it using shared docker socket. I wanted to make a patch for rancher community catalog (to use shared docker socket), but not sure if this is the original intentions from the owner.

Thank's

**Comment by sjoerdmulder** [comment]
Thanks for your question! I don't maintain the Rancher catalogue. 

But to be honest i also don't use Teamcity anymore, and i'm also not maintaining this repo anymore.

From my memory i have used this runner using docker-in-docker with the `--priviledged` flag set. So it might need some extra modifications to work with a shared docker socket.

**Comment by lucernae** [comment]
Thank's. do you use another alternative CI or just doesn't use Teamcity in particular anymore?

**Comment by sjoerdmulder** [comment]
We switched to Gitlab CI
