### ISSUE TITLE
auplink not found in path

### ISSUE THREAD

**Issue by rancohen1** [sjoerdmulder/teamcity-agent-docker#3]
I got these when running docker build inside the agent

`Error removing intermediate container 8bf41e1ba5c5: nosuchcontainer: no such id: 8bf41e1ba5c5bc26fb40ce083b23b17fb2be3f811368e61b12301cbdef15a05c`

I ran the image watch the output as such:
`docker run -it --rm -e TEAMCITY_SERVER=http://localhost --privileged sjoerdmulder/teamcity-agent`

and noticed right at startup (I think its wrapdocker saying this):
`ERRO[0001] Couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH
had to apt-get install aufs-tools`

So I created my own image:

```
FROM sjoerdmulder/teamcity-agent
RUN apt-get update && apt-get install aufs-tools && rm -rf /var/lib/apt/lists/*
```

and now it works, am I missing something?

**Comment by sjoerdmulder** [comment]
I have just commited your fixes to the master branch.

Thnx for the report!
