### ISSUE TITLE
Are you now using docker:dind

### ISSUE THREAD

**Issue by bladnor** [sjoerdmulder/teamcity-agent-docker#5]
Hi

In your readme you wirte that you use dind from jpetazzo. But jpetazzo writes that his work is now obsolete because there ist docker:dind. Is your teamcity-agent-docker updated to use docker:dind or still using the stuff from jpetazzo?

Thanks Roland

**Comment by nafg** [comment]
@bladnor it looks to me like it's "using" neither, it's just doing basically the same thing that docker:dind does: 

https://github.com/sjoerdmulder/teamcity-agent-docker/blob/master/Dockerfile#L35-L36

**Comment by sjoerdmulder** [comment]
Yes, I copied the script from jpetazzo back in the days, so it's not using any of those, it is using:

https://github.com/sjoerdmulder/teamcity-agent-docker/blob/master/wrapdocker
