### ISSUE TITLE
Reaping problem (java defunct process)

### ISSUE THREAD

**Issue by etki** [sjoerdmulder/teamcity-agent-docker#8]
Hi.

First of all, i know that this is PITA-problem you don't have any relation for nor intention to create. However, any `docker restart` call has a chance to turn container with agent into dead one with `[java] <defunct>` command line in `docker top` output. As far as i know it means that java process (i.e teamcity agent) has spawned some children, but never cared about them, so they went to orphanage ([related stackoverflow question](http://askubuntu.com/questions/201303/what-is-defunct-for-a-process-and-why-it-doesnt-get-killed)), and it is a [common problem](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) within container infrastructure (since entrypoint is always the number 1 process). The defunct container is pretty useless and dead: you can't restart, enter or delete it, and only a complete reboot might help. As far as i can tell, this should be simply solved by inheriting from phusion/baseimage, JetBrains, however, should be notified about as well (i hope i'll have a minute to push detailed issue there as well).

**Comment by sjoerdmulder** [comment]
Yes, i currently don't experience this issue, except for issue https://github.com/docker/docker/issues/18180
